XENONnT/WFSim

core.py

Using snakeviz and line profiler identify some easy to improve issues in the code.

Performance Optimizations

---

strax_interface/fax.py
strax_interface/fax_interface.py

This pull request add the self triggering of the digitizer for raw records.
In fax the raw_data is extended with the trigger window of 50 samples in both directions and filled with noise and the digitizer baseline.
In fax_interface the raw_data is taken directly from fax and written to records

Update for strax

---

strax_interface/fax.py
strax_interface/fax_interface.py

Adds a saturation cutoff and moves the last file path to the config

Strax updates

---

setup.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py
wfsim/utils.py

Create an independent resource loading class, advantages would be:
1) Straight forward file loading and treatment, and can be tested before strax context init
2) Possibly making switching files easier
Disadvantages would be it won't be tracked by strax options, might need to come up a way to feed the file names back to strax.

Split resource loading from main code

---

wfsim/strax_interface.py

This pull request:
* Adds the possiblity to read in geant4 output directly. It uses nestpy to go from energy deposition to number of photons and electrons

Added possibility to read in geant4 output

---

notebooks/test_simulator.ipynb
tests/test_strax_interface.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py
wfsim/units.py
wfsim/utils.py

This would be focusing on how to properly treat overlap pulses.
Main prepose is implementing software trigger/zero length encoding (ZLE) to generate raw data pulses. 
- To facilitate this, functional call of RawData in core is now a generator of digitized data w/ ZLE for individual PMTs, in order of instruction then channel then time.
To deal with possible overlapping instructions, and rid of event structure. Data are now produced in chunks determined by instruction input.
- Truth information is extracted for each instruction
TODO:
Peak simulator needs to be recoded

Dealing with overlapping pulses

---

notebooks/bias_smearing_demo.ipynb
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

Putting back instruction from csv

Bia Smearing Demo and Bug Fixes

---

wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

This pull requests add the needed things to run the waveform simulator with a XENONnT configuration.
* Open issue: light yield maps crash during interpolation so now are fixed values
* Some files are to large to host on github, so we need to put them somewhere else and the paths in strax_interface and load_resource need to be set by hand
*Strax also doesn't work with a nT configuration at the moment, so some changes to pulse_processing in strax are also needed before it works

Add features required for XENONnT configuration

---

notebooks/Fax_Tutorial.ipynb
notebooks/test_simulator.ipynb
requirements.txt
setup.py
tests/test_wfsim.py
wfsim/core.py
wfsim/load_resource.py
wfsim/pax_interface.py
wfsim/strax_interface.py
wfsim/utils.py

This fixes the Travis build and improves integration with straxen.
* Make WFsim use straxen's functions for loading resources and building maps. I moved several of the improvements you made (thank you!) to the corresponding functions in straxen. (If you make straxen pull requests for these in the future, we will all benefit from the improvements.)
* Load the Resource class using a separate `load_config` function, which keeps a cache to avoid reloading the same config. The current implementation with a singleton class would only allow loading one configuration per python session -- if I'm not mistaken.
* Add a XENONnT simulation test.
* Fix default paths to point to github, not /dali. 
* Fix reading instructions from csv. We now explicitly check that the csv produces the correct dtype. If …

Straxen integration and test build fix

---

setup.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

The channel assignment using the pattern map is not fully utilized so far. It is time to remove the pattern function that mostly just for my personal usage, and back to pattern map interpolation.

Remove outdated per pmt pattern

---

setup.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py

Another look into possible performance boosts as it is taking ~30 minutes to simulate 100 events with those neutron inputs.
In the initial https://github.com/zhut19/WFSim/commit/df87e55b399d8732fd946af0798d8db7fb59c079 commit, we upgraded in three places, adding current, interpolating spe distributions, and loop of s2 instructions for electron timings. With those three the simulation time is almost reduced by half. But the performance in digitization and ZLE is not improved from this upgrade.

Not fast enough for neutron sim

---

requirements.txt
tests/test_wfsim.py
wfsim/core.py
wfsim/strax_interface.py

This pull request fixes the noise implementation to actually work

Fixes noiose

---

.travis.yml
tests/test_core.py
tests/test_wfsim.py
wfsim/core.py

Hi @petergaemers! In https://github.com/XENONnT/WFSim/pull/65 an unintended index error was introduced. It took me some time to figure out because with numba on it's harder to debug. It just died. Running with ``--debug`` only showed a segmentation fault.
When I found the problem, I actually spend most time on writing a test that should catch this in the future. Its a pain to write these things I admit. Hope it helps.

add test for segmentation fault in noise handling

---

wfsim/core.py

Looks like we missed to change `self.config` to `config` in the previous PRs https://github.com/XENONnT/WFSim/pull/94 and https://github.com/XENONnT/WFSim/pull/83.

Fix get_n_photons

---

tests/test_wfsim.py

Fix the commit id of the 1t config.

Fix 1t config for test

---

.bumpversion.cfg
HISTORY.md
setup.py
wfsim/__init__.py

Get ready for a new release that from now on is tracked [also in pipy](https://pypi.org/project/wfsim/). For the future, it would be great if we add a comment to the history such that we know which update was done when.

Make release

---

wfsim/load_resource.py

This should follow to the PR https://github.com/XENONnT/private_nt_aux_files/pull/33.
For S2 map please revisit all appearances of the S2 pattern and ly map since it is no longer normalized! You can see https://github.com/XENONnT/private_nt_aux_files/pull/33 if you want to see how to open the map and how it looks like summed over all PMTs.
Don't merge this right now and add map related changes please. Thanks!

Update nT pattern maps

---

wfsim/core.py

The truth tries to readout a variable self._electron_timings for the number of produced electrons. This PR reintroduces this variable since it wasn't stored anymore in pr #103

Reintroduce self._electron_timings for truth

---

wfsim/strax_interface.py

Epix isn't imported, but it is used

Fix missing epix import

---

docs/source/conf.py

Ignore errors in notebooks on build. 
For some reason shpinx tries running a notebook, with this PR, we will ignore any related issues because of that.

allow errors while building docs

---

HISTORY.md

For e.g. https://pypi.org/project/wfsim/ it is nice to keep a record of the releases published. This is based on the history. This PR updates that history for the last two releases.

update history of releases

---

wfsim/strax_interface.py

maybe fixing chunking issue

---

wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

Debugging of PMT afterpulse class

Fix PMT Afterpulse

---

requirements.txt
wfsim/strax_interface.py

The lineage should not depend on this, right?

Don't track the timeout

---

.bumpversion.cfg
HISTORY.md
setup.py
wfsim/__init__.py

Make v0.5.0 release

---

wfsim/strax_interface.py

Fixes https://github.com/XENONnT/WFSim/issues/144

No default for gain_model_nv defined in the class

---

.github/workflows/coveralls.yml
.github/workflows/test_package.yml
.travis.yml
setup.py
tests/test_context.py
tests/test_contexts.py

Add a failing test to not run into #144 again
This should be fixed in #145

add tests for #144

---

wfsim/load_resource.py

Fixing the issue that loading map data from the direct path is not working.
Reordering the downloading method, using the installed package before using the mongo downloader.

Fix load resource

---

.github/workflows/coveralls.yml
.github/workflows/test_package.yml
.travis.yml
requirements.txt
wfsim/core.py

As noticed by Daniel and Andrii the last instruction was (not always?) read out. Here I add a final digitization step to make sure we get all data

Fix missing last instruction

---

.github/workflows/coveralls.yml
.github/workflows/test_package.yml

Reinstate testing to use the latest zstd

fix zstd for testing

---

wfsim/core.py
wfsim/strax_interface.py

Fixing bug of truth outside chunk time, but this is really due to a bug introduced in #161 that gain is 10 times smaller than it should be.

Truth chunk patch

---

tests/test_contexts.py

Master broken after straxen changes, this should fix it.

No context testing for py3.6

---

wfsim/core/afterpulse.py
wfsim/core/rawdata.py

As stated in #140, for large S2s the number of electron afterpulse instructions exceeds the size of the instruction buffer. We will try to fix it here by reducing the amount of instruction we produce.

Make less ele ap instructions

---

extra_requirements/requirements-tests.txt

Bump straxen

---

extra_requirements/requirements-tests.txt

Bump the version of strax(en) used in testing

Bump strax(en)

---

extra_requirements/requirements-tests.txt

version bump

---

extra_requirements/requirements-tests.txt

See title, requires https://github.com/XENONnT/WFSim/pull/316

Test with latest straxen

---

pytest.ini
wfsim/core/pulse.py
wfsim/pax_datastructure/datastructure.py
wfsim/strax_interface.py

Currently have about 100 warnings, let's reduce that
similar to https://github.com/XENONnT/straxen/pull/915

reduce warnings

---

extra_requirements/requirements-tests.txt

Test with straxen 1.5.0

---

extra_requirements/requirements-tests.txt
wfsim/core/s2.py
wfsim/load_resource.py

- fixed CIV implementation
- fixed average drift velocity map implementation with normalization for cathode-gate drift time at R=0
- removed potentially dangerous code duplication

Fix CIV and average drift velocity implementation

---

extra_requirements/requirements-tests.txt

Test with latest strax

---

.github/dependabot.yml

wfsim needs a new maintainer

---

.github/dependabot.yml

Just so that we don't forget to rotate :)

Add new WFSim maintainer
