.travis.yml
tests/test_strax_interface.py
wfsim/fax.py
wfsim/fax_interface.py

This will:
* Add a unit test that verifies the simulator does not crash.
* Add a check in the strax interface that chunks of raw_records passed to straxen are sorted by time and sufficiently well-spaced. 
* Strax, or rather the low-level processing algorithms in straxen, require(s) this. The DAQReader does work for to ensure it, but here we're not reading from the DAQ.
* If you pass unsorted or (nearly) overlapping chunks of records to strax it can cause a hang until the mailbox timeouts expire (I'm not exactly sure why). 
* I did not want to dig too deeply to figure out why we got non-sorted or overlapping chunks in some conditions, so I just added a check and made it throw an exception if we see the problem. I hope a future fix would solve the problem and remove the check.
* Replace the …

Add tests, njit add_current

---

wfsim/core.py
wfsim/strax_interface.py

This pull request fixes a a bug in the self triggering mechanism. The self triggering window of the digitizer was confused with the length of the PMT response. This caused the simulated pulses to appear in the region Strax uses to calculate the baseline leading to negative areas.

Fixes selftrigger mistake

---

wfsim/__init__.py
wfsim/core.py
wfsim/pax_interface.py
wfsim/strax_interface.py

New function to read Geant4 files. We are now using the individual positions of each interactions and the corresponding energy depositions. The event number is taken from the Geant4 root file as well. The events are now separated by a constant time difference. I think this can be changed in the future to be more efficient. 
Things to do next:
-  get the recoil type (ER, NR) from the interaction
-  get the interacting particle for NEST from the Geant4 file
- do we need some clustering like in nSort?
- Why are there cy > 1 values in core.py?

Update G4 and PAX interface

---

setup.py
wfsim/core.py
wfsim/pax_interface.py
wfsim/strax_interface.py

Event_number in instruction was used as a temporary solution to chunking, however, event_number  is intended to be reserved for other purposes. While chunk should be done automatically by 'time'.
This pr also try to solve 
1) Crash due to unable to yield when event_rate is set above 100 Hz and cut off time set > 0.1 seconds. 
2) Long term effect e.g. photo ionization (PI) electrons are saved into instruction buffer as well as the truth.
3) Double photon electron is propagated to the truth output as well.
Immediate effects are:
1) Instruction input can be unsorted now
2) Must specify chunk_size in config, (especially when not using build-in random instruction)
3) Running might be just a tiny bit slower.
For the future:
1) Delay coincidence can be implemented very easily.
2) Long term …

Redesign chunk mechanism

---

wfsim/core.py
wfsim/strax_interface.py

This should allow passing _sort_check consistently by adjusting 'right_raw_extension', currently set to be twice the minimum gap in _sort_check.
Right_raw_extention control gap between instructions not the eventual wf, as pmt ap and pulse width will make wf gap smaller.

fix chunk during a pulse

---

notebooks/Fax_Tutorial.ipynb
notebooks/test_simulator.ipynb
requirements.txt
setup.py
tests/test_wfsim.py
wfsim/core.py
wfsim/load_resource.py
wfsim/pax_interface.py
wfsim/strax_interface.py
wfsim/utils.py

This fixes a few things in the truth info writing.
* Due to an indexing quirk, the truth buffer was never actually marked as cleared in `final_results` of `ChunkRawRecords`. As a result, there were many duplicate entries in the truth output for long datasets.
* There was a [mutable default](https://docs.python-guide.org/writing/gotchas/) for `truth_info` in RawData. I don't think this is actually used, so perhaps we can just remove it instead of using the None-default trick?
* Maybe this was a feature, not a bug, but for afterpulse-like peak the t_first_electron etc. fields were not set to NaN when there are no electrons. Since the truth buffer gets reused without being cleared, I think this would lead to values from old peaks showing up in the truth for new peaks. Just let me know if I …

Truth writing fixes

---

wfsim/core.py
wfsim/strax_interface.py

This fix is implemented by @petergaemers.
For signals that were not detected, no truth info was written as the condition on line https://github.com/XENONnT/WFSim/blob/02bcef02c83b42af5daae1df969913078dbba9a2/wfsim/strax_interface.py#L226 was never satisfied for np.nans.
This resulted in fewer S1's in the truth than we requested in the instructions.

edit truth handing for non-detected signals

---

wfsim/load_resource.py

Amends load_resource.py to allow different filenames for light yield maps, etc to be passed via the config. Default hard-coded files are preserved. Unity light yields are helpful for understanding reconstruction efficiencies.
Note: I also added "placeholder_map.json" to strax_auxilliary_files. I think you could try this as the default for nT instead of doing [this](https://github.com/XENONnT/WFSim/blob/cce8748785cf1a208c44be6df84655b77ad60f80/wfsim/core.py#L247) but I didn't want to mess with it.

Allow config override of files

---

setup.py
tests/test_wfsim.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py
wfsim/pax_interface.py
wfsim/strax_interface.py

The strax has updated to [v0.9.0](https://github.com/AxFoundation/strax/releases/tag/v0.9.0), requiring 
chunk class (dictionary of chunk classes) for return.
Other updates:
- Remove gains from config, instead use to_pe file to calculate gain.
- Add the secondary signal from the photo-electric effect of the gate, only for S2. Matching S2 pulse shape by eye.
- Fix some issues with truth output when there're dead pmts.
- Update pax_interface so it can work again.

Catch up strax

---

requirements.txt
setup.py
wfsim/__init__.py
wfsim/core.py
wfsim/load_resource.py
wfsim/pax_interface.py
wfsim/strax_interface.py

Adding field distortion feature to core simulation.
Use SR1 nn tf part 1 for xenon1t
Return 0 correction for xenonnt
The results are shown below, observed positions with given points on a circle with r=[10, 20... 50]. The observed positions are stable after a few iterations, (as fdc map is not asking true position as input), more solid color represents later in the iteration (max=6)
Other fixes along with this pr:
Increase pax_interface truth buffer size,  because unlike strax, it's not being copied and cleared at the end of each chunk.
Check the length of instruction dtype names instead of instruction itself for extra columns, as now instruction is a structured array by default.

Add field distortion effects w/ FDC map

---

wfsim/__init__.py
wfsim/core.py
wfsim/raw_optical.py
wfsim/strax_interface.py

This pull request adds:
*  Adds the option of using optical mc data to use as instructions for simulation
To use register wfsim.RawRecordsFromFaxOptical and set the context option "optical" to True
There is still quite some needlessly double code in here. So I'll need to clean it up more

Update for instructions from optical mc

---

notebooks/Fax_Tutorial.ipynb
wfsim/core.py
wfsim/strax_interface.py

This pull request adds high energy and sum signals.
For this a change needed to be made in the plugins. Since high energy channels are not in XENON1T the plugins for 1T/nT are split off. So to switch between detectors register different plugins rather than setting the detector field as an option.
The sum signal is stored as part of the high energy channels, although it would in reality be part of the aquisition monitor
Note there is a not very pretty hard coded number of channels currently in https://github.com/XENONnT/WFSim/blob/455a481a44bc0ac6926f291e4e2148cb382c00dd/wfsim/core.py#L877
Usage:
```
strax.Context(
storage=strax.DataDirectory('./strax_data'),
register=wfsim.RawRecordsFromFaxNT,
config=dict(detector='XENONnT',
fax_config='https://raw.githubusercontent.com/XENONnT/' …
```

Adding features needed to support high energy channels for XENONnT simulations

---

wfsim/core.py

Two issues related to S2 photon channel distribution. One is that the generated s2 photon timings are ordered, combined with channel distribution code, we ended up with more concentrated photons in each channel.  While in nT channel distribution, the now vectorized map interpolation is not fully used. Multiple patterns are returned for each x-y point.

S2 related bug fix

---

wfsim/core.py
wfsim/strax_interface.py

I would like to add methods for nVeto pulses. It strongly depends on the Geant4 optical simulation.
To prepare this implementation and test, I fixed obvious errors on 'optical', and add workaround lines to be fixed for the future.

Fix optical

---

wfsim/strax_interface.py

Hi WFSim experts! 
**What**
I noticed that the truth is not always sorted by time. I wondered if I should ask/file an issue but actually it looks like it's quite straight forward to solve (assuming I'm correct which I might not be). 
We could even delete the ` truth.sort(order='time')` call a few lines above. Let me know what you think.
Perhaps there is a good reason why the truth is not sorted by time, please consider this PR as an Issue/question in that case.
**Why?**
Reason for this PR is that I'm writing a matching `LoopPlugin` that needs sorted 'time' information. Of course this is trivial to make in case you guys think this is not to be handled as in this PR. Let me know what you think:
```python
class SortTruth(strax.Plugin):
depends_on = 'truth'
provides = 'truth_sorted'
def …
```

Sort _truth by time

---

tests/test_wfsim.py
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

Use https://straxen.readthedocs.io/en/latest/config_storage.html#downloading-xenonnt-files-from-the-database to get nT files.
For nT, we can now use (if we are on the latest straxen master) the database to get the required files. All the files from https://github.com/XENONnT/strax_auxiliary_files and https://github.com/XENONnT/private_nt_aux_files are uploaded to the database. We should be able to download those files like this. 
Some testing from the WFSim experts would be appreciated because they are most likely much better in isolating potential issues than I am.

use files database

---

wfsim/strax_interface.py

WFSim uses PMT ID started on 0 for also nVeto option.
However, it is convenient to return the correct ID (2000--2119) is useful for analyst.
I've checked it works, please review the lines.

Return correct PMT ID for nVeto

---

wfsim/strax_interface.py

I added 'g4id' in truth using optical simulation. (In the current implementation, they are empty.)
It works.
In the far team-D telecon, I said unique event ID is enough to match TPC and nVeto events, but it is not correct.
Multi 'raw_records' and 'raw_records_nv' are created in one Geant4 event. In other words, more raw records are generated for one truth. We cannot match that because we don't know which truth created one specific raw record.
(Using event time, we can guess that but I think it is not straight-forward solution.)
Am I missing important thing? Please give me a comment and let's start a discussion.

Geant4 event ID in truth

---

wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

To keep consistency with MC and epix. Sorry @petergaemers for the confusion.
This also solves a failure when trying to run 1T sims, since the renaming to `xenonXt_detector` hadn't been propagated in this case.

Back to old detector naming

---

wfsim/load_resource.py

This PR is following https://github.com/XENONnT/private_nt_aux_files/pull/23.
---
**What has changed?**
For `XENONnT_s1_xyz_patterns_corrected_qes_MCva43fa9b_wires.pkl`:
- actual electrode wires are used within Geant4 instead of thin disks
- QEs of the PMTs as reported by Hamamatsu were added. We assume that these QEs already include the DPE judging by the way the QEs are measured. Therefore, we should divide by the corresponding DPE value like: `map/(1 + DPE)`
- One can express the saved value as: `APE = LCE(x,y,z)*corrections*QE` (see [this note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:althueser:20201014_optical_simulation_s1_absl))
For `XENONnT_s2_xy_patterns_topbottom_corrected_qes_MCva43fa9b_wires.pkl`
- actual electrode wires are used within Geant4 instead of thin …

Update nT pattern maps

---

wfsim/core.py

Our old `"xenonnt_detector"` was reintroduced in here: https://github.com/XENONnT/WFSim/pull/83
@jorana @petergaemers Shouldn't the test have triggered something in this case, since `ly` isn't called?
I will push a new tag after this is merge, if you agree.

Correct detector naming

---

wfsim/core.py

We have been ignoring horizontal diffusion so far, which might impact the S2 pattern.
The added function in S2 pattern generation would now output diffused patterns, but with naive calculations
- One can set an additional parameter `diffusion_constant_liquid_horizontal` in config to enable this
- We will create updated xy positions for all electrons in each S2, the new pattern is calculated averaging over those new positions.
- Positions outside the TPC radius will be ignored, as the output will be the average over all other positions.
- It's not a weighted average, as an electron with 50 photon carries the same weight as an electron with 20 photon
- There's no enforced time-positon correlation at this per electron level.

add h-diffusion function

---

.github/workflows/Pipi.yml
.github/workflows/coveralls.yml
.github/workflows/test_package.yml
README.md
docs/pull_request_template.md
tests/test_core.py
wfsim/core.py

In this PR:
- I added github actions to do the CI testing, github actions are much faster than travis, allowing effective testing instead of everlasting waits and eventual ignoring the tests all together
- It also add a github actions service for doing the coveralls uploads, this also tests the repo but simultaneously checks how many lines are covered by the tests
- To remind everyone of tests, etc, I've added a template to remind the author if he/she can add doc-strings and tests, however tedious it may be,
- It's now pip installable!
- The readme has been updated with the badges corresponding to these tests:

Add github actions to repo

---

tests/test_load_resource.py
tests/test_wfsim.py
wfsim/core.py
wfsim/strax_interface.py

- Remove SPE spectrum normalization, the new SPE spectrum will be centered around 1 PE
- +1 to SPE indexing, to avoid odd value at -1 PE
- Fix the issue with getting transverse diffusion constant from config, use `dict.get(x)` instead of `getattr(dict, x)`
- Make sure S2 like after pulses have Z below 0
- Fix divide by zero warning in strax interface.

Miscellaneous fixes

---

wfsim/strax_interface.py

```python
/home/angevaare/software/WFSim/wfsim/strax_interface.py:645: SyntaxWarning: "is not" with a literal. Did you mean "!="?
for data_type in self.provides if data_type is not 'truth'}
```
Fix this warning

Fix non-literal compare for str

---

tests/test_core.py
wfsim/core.py
wfsim/load_resource.py
wfsim/strax_interface.py

I pushed the changes in the `Resource` class for loading the GARFIELD maps according to the simulated liquid level, respecting the format introduced in https://github.com/XENONnT/private_nt_aux_files/pull/46. I found this was a better place than the ` luminescence_timings_garfield` function, but let me know if you disagree.
I also changed the default map to load.

Load GARFIELD map according to liquid level

---

notebooks/Getting_started_wfsim.ipynb

See issue #134 for more info. 
This is just to ensure the typo in quanta generation doesn't propagate to others' codes, namely that the generation of quanta for both photons and electrons should happen in a single step, then separated out after the fact.

conserve total quanta in tutorial

---

wfsim/strax_interface.py

Missed old way to refer to writing out nv data.
nv is always in data type whether you want it or not. Use the targets option instead

Fix nveto readout

---

wfsim/load_resource.py

When running full chain, we temporarily set the detector in config to XENONnT_neutron_veto, and won't be needing electron after pulses resource. And would get a key error when we do enable electron afterpulse. So this PR will tuck the load electron afterpulse resources under the condition detector is either XENON1T or XENONnT.

Tuck load ele ap in tpc conditions

---

.github/scripts/create_readonly_utilix_config.sh
.github/workflows/coveralls.yml
.github/workflows/test_package.yml
docs/pull_request_template.md

This PR allows WFSim to pull configs form the database in order to be fully tested. This should increase the coverage and make it easier for the developers to spot potential issues as github actions would work just as well as doing local tests.
For example #152 will be much more useful if this PR is merged.
There is a caveat which the developers should be aware of since this will cause work (less then in the current state but still, they are the ones in charge to fix those things).
In order to have the test also being able to run from a remote fork, the tests need to (stay) drafted as if there is a possibility that one does not have access to the database. We make sure this is the case using the famous line:
```python
if not straxen.utilix_is_configured():
return
```
The developers should …

use database access to increase coverage of tests

---

wfsim/load_resource.py

For [empty configs like this](https://github.com/XENONnT/WFSim/blob/c2d1f17551ab7954fa5def83b3ff810de91ed3ef/wfsim/load_resource.py#L93) we cannot summon files out of thin air 🧙 . Therefore, we just need to skip those. Otherwise we are going to try loading things from places we are sure we cannot find them.
Lets wait for #159 to be merged, then should be fine again.

Fix #157 for empty files

---

tests/test_wfsim.py
wfsim/core.py

Following up on https://github.com/XENONnT/private_nt_aux_files/pull/56, bin sizes are added to the pmt afterpulsing file. Here we change the hardcoded bin size to the ones saved in the resource file.
TODO:
~Update this file for XENON1T~

Following up the change in pmt ap file

---

tests/test_wfsim.py

In https://github.com/AxFoundation/strax/pull/440 I made the context a bit more strict on the allowed config options. If one says that per-run-defaults are not allowed, we can get great speed improvement.
However, if you use 1T plugins (with per run defaults) this will cause errors:
See e.g. the base env:
https://travis-ci.org/github/XENONnT/base_environment/builds/771769395
As such, we need be explicit that it is ok to use per run defaults for 1T simulation.

Patch 1T custom context

---

wfsim/core.py

If each channel/array has individual timing distribution, it will be effectively scrambled due to call of `unique` function here: https://github.com/XENONnT/WFSim/blob/s1_ch_sorting/wfsim/core.py#L75 . 
To avoid this unwanted behavior, explicit sorting is performed in S1 class.

Introducing sorting by channel number to preserve timing in S1s

---

requirements.txt

Straxen 0.19.0 is bugged and shouldn't be used, see e.g. the current failing test on master

Straxen 0.19.0 is bugged

---

wfsim/core.py

@dantonmartin had reported a very small negative bias even with noise disabled. This is caused by that the interpolation on inverse survival function (isf) of the SPE spectrum returns value shifted down by half a bin size (0.01 PE) of the input SPE spectrum which is 0.005 (PE).
This pr will use 'next' to interpolate the isf, so that we can get back exactly the distribution of the input spectrum. (But we do lose sub 0.01 PE resolution, which is acceptable)

Fix the 0.5% bias in gain sampling

---

tests/test_contexts.py
tests/test_wfsim.py
wfsim/utils.py

In optical_adjustment we split peaks if they are too long, adding a new instruction for the remainder. However there is a mistake causing the split peak to not be split and the remainer to be still added afterwards
This fixes the splitting function

Fix optical readout

---

wfsim/strax_interface.py

I'm really sorry to forget to push the last bug fix.

Bug fix for wrong place to write dtype of numpy array for empty return case

---

tests/test_core.py
wfsim/core/rawdata.py
wfsim/load_resource.py

Remove the temporary measure of flattering noise sample from XENON1T for XENONnT. So with the proper noise file, the noise would be sampled from individual channels instead of mixing all together.

Use real noise

---

requirements.txt
wfsim/strax_interface.py

Due to a bug fix in strax PR #569 many config options in WFSim will now produce warnings. This PR suppresses these warning by explicitly setting the infer_dtype to False wherever the type of the config Option would have been inferred from the default value in the future.
This breaks backward compatibility with older strax versions since the infer_dtype keyword did not exist before, so I have pinned the strax version in the requirements to be above the next version.
A better alternative to this PR would be to set the type explicitly for all options, but in case you dont want to commit to a specific type for all of your plugin options this PR will just disable the auto inference of types from the default values.

add infer_type=False to all strax.Options

---

wfsim/strax_interface.py

Loop over nVeto data types only when `nveto` is one of the targets to simulate, otherwise we run into errors when using the mc_chain context with nVeto set to false: we're requesting `result_nv` without having defined it earlier (because `nveto` it's not in targets), while the `RawRecordsFromMcChain` plugin provides with all data types for nVeto and TPC.

Fix nVeto dtypes handling in RawRecordsFromMcChain

---

tests/test_load_resource.py
wfsim/core/s1.py
wfsim/core/s2.py
wfsim/load_resource.py

As @terliuk found out, the turned-off PMT in LCE must match the ones in the `to_pe` model. This is especially true for S2s, LCE under 'OFF' PMTs is smaller, while the relative probabilities in the 'ON' PMTs are higher.

Recompute lce on the run

---

wfsim/core/s2.py

Align naming of `s2_aft_sigma` with currently updated settings: https://github.com/XENONnT/private_nt_aux_files/pull/112 I think there's no backwards compatibility issue.

Rename s2_aft_sigma config

---

wfsim/core/s2.py
wfsim/load_resource.py

Samples optical propagation delays in the gas phase from a G4 simulated data.
The S2 pulse workflow is a bit changed; photon channels sampling is now independent from photon times. This was needed so that photon time delays can be added based on whether they are detected at top/bottom arrays.
!To add this effect it uses a local aux file for now, the file will be added to private_nt_aux repo!
**WFSim needs you:**
- Please add a test for this PR, as a bare minimum, make sure it's covered in coveralls!
- Can you add a docsting to all your functions?
*Pay attention:*
- Due to databases being needed for testing, making a PR from your own fork will typically NOT run the tests. If you then merge master might break

S2 optical prop

---

.github/workflows/Pipi.yml
.github/workflows/pytest.yml
.readthedocs.yml
extra_requirements/requirements-tests.txt
setup.py

Follow AxFoundation/strax#636, XENONnT/straxen#906, let's drop support for older python versions.
For nestpy, see the discussion in https://github.com/NESTCollaboration/nestpy/pull/80
Also see https://github.com/NESTCollaboration/nestpy/pull/80

up py version

---

wfsim/core/afterpulse.py

One of the optimizations in #15 on the `pulse` class created this bug, that PMT afterpulse are ordered in channel number instead of from the channel created them.
https://github.com/XENONnT/WFSim/blob/c50a7a2b7c67b37755e1d073683f902c9424f111/wfsim/core/pulse.py#L67
To resolve this, the returned values need to be sorted by the channel numbers.

PMT afterpulse not sorted by channel

---

wfsim/core/afterpulse.py
wfsim/core/pulse.py

The double photo-electron in PMTs also contributes to generating PMT afterpulse, in this pr, we store a boolean array noting photons emitting dpe, in the last step of generating S1s and S2s. While we double the PMT AP probability for those photons when generating PMT afterpulses.

Double PMT ap probability for photons emitting double PE.

---

wfsim/core/s2.py

Drift velocity maps should use interaction position and not final position in XY. In particular, this resulted in slightly off shape near the bottom edge. This shape did not correspond to the one, when maps are read directly. In previous PR https://github.com/XENONnT/WFSim/pull/338 this was fixed on one place, but not in other.

Fix drift velocity map usage (again)

---

wfsim/strax_interface.py

I just noticed - to my surprise - that blosc is still the default compressor, whereas  we can be about ~2x squeezer than that at almost no performance loss:
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:ivyli:lossless_compression

Change default compressor

---

wfsim/core/rawdata.py

I just ran into this error 
```Traceback (most recent call last):
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/2022.04.2/anaconda/envs/XENONnT_2022.04.2/bin/pema_straxer", line 273, in <module>
sys.exit(main(args))
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/2022.04.2/anaconda/envs/XENONnT_2022.04.2/bin/pema_straxer", line 193, in main
for i, d in enumerate(get_results(run_id, target)):
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/2022.04.2/anaconda/envs/XENONnT_2022.04.2/bin/pema_straxer", line 181, in get_results
yield from st.get_iter(**kwargs)
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/2022.04.2/anaconda/envs/XENONnT_2022.04.2/lib/python3.8/site-packages/strax/context.py", line 1321, in get_iter …
```

Off by one in noise

---

wfsim/core/s2.py
wfsim/load_resource.py

This code replaces random S2 AFT sampling done by Peter to scale mean AFT from maps to match the average from data. This way we preserve information about impact of LCE in general and switched off PMTs in particular. This PR has to be merged together with the corresponding private repo PR https://github.com/XENONnT/private_nt_aux_files/pull/195.

Added scaling of S2 AFT according to value from config

---

extra_requirements/requirements-tests.txt
tests/test_wfsim.py

Seems like https://github.com/XENONnT/epix/pull/53 requires a new key not included in the tests - I'm a bit surprised this only now shows up.

Fix broken tests

---

.github/workflows/pytest.yml
.gitignore
tests/test_contexts.py
tests/test_load_resource.py
tests/test_wfsim.py
wfsim/core/rawdata.py
wfsim/core/s2.py
wfsim/load_resource.py
wfsim/pax_interface.py

Fix a few problems and testing for #363

refactor #363

---

wfsim/strax_interface.py

Positions of the primary particles from G4 are recorded in the truth.
**Can you give a minimal working example (or illustrate with a figure)?**
The notebook linked below can be used for tests. Requirements:
- **newtruth** branch of **epix** [(PR #56)](https://github.com/XENONnT/epix/pull/56)
- **newtruth** branch of **WFSim**
[/dali/lgrandi/pkavrigin/2022-06-02_TestWFSimTruth/Test_NewTruth.ipynb](/dali/lgrandi/pkavrigin/2022-06-02_TestWFSimTruth/Test_NewTruth.ipynb)

Save Geant4 primary position in truth

---

.github/workflows/pytest.yml
extra_requirements/requirements-tests.txt
tests/test_wfsim.py
wfsim/strax_interface.py

Follow https://github.com/XENONnT/straxen/pull/1079

Url config minimal patch

---

.github/workflows/Pipi.yml
.github/workflows/pytest.yml
.readthedocs.yml
extra_requirements/requirements-tests.txt
setup.py
tests/test_contexts.py
tests/test_wfsim.py
wfsim/__init__.py
wfsim/contexts.py

Together with https://github.com/XENONnT/straxen/pull/1320, to disentangle straxen and wfsim, and make the software environment easier. Because we do not need to maintain compatibility of wfsim inside both wfsim and straxen, e.g. the nestpy(needed by wfsim) currently does not support py3.11(https://github.com/NESTCollaboration/nestpy/issues/104), so we can not update straxen to support py3.11, which is not reasonable.
**WFSim needs you:**
- Please add a test for this PR, as a bare minimum, make sure it's covered in coveralls!
- Can you add a docsting to all your functions?
*Pay attention:*
- Due to databases being needed for testing, making a PR from your own fork will typically NOT run the tests. If you then merge master might …

Move all simulation contexts to WFSim

---

.bumpversion.cfg
HISTORY.md
setup.py
wfsim/__init__.py

Just bump version. A minor bump because we dropped support for py3.8.

Bump to v1.2.0

---

wfsim/core/s2.py

Inspired by solution in fuse [here](https://github.com/XENONnT/fuse/pull/171), trying to solve the [s2 photon timing bug](https://github.com/XENONnT/WFSim/issues/425). The detailed mechanism why it fixed things is unclear but we don't care much for a legacy package. Below is before and after the fix:
**WFSim needs you:**
- Please add a test for this PR, as a bare minimum, make sure it's covered in coveralls!
- Can you add a docsting to all your functions?
*Pay attention:*
- Due to databases being needed for testing, making a PR from your own fork will typically NOT run the tests. If you then merge master might break

Fix s2 photon timing bug

---

extra_requirements/requirements-tests.txt

Use base_environment for pytest, following https://github.com/XENONnT/base_environment/pull/1487.
**WFSim needs you:**
- Please add a test for this PR, as a bare minimum, make sure it's covered in coveralls!
- Can you add a docsting to all your functions?
*Pay attention:*
- Due to databases being needed for testing, making a PR from your own fork will typically NOT run the tests. If you then merge master might break

Deprecate the usage of `XENONnT/ax_env`
